spring:
  application:
    name: recipe-orchestration-api
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:recipedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory:
              type: local-heap

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example.recipeapi: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/recipe-api.log

external:
  api:
    recipes:
      url: https://dummyjson.com/recipes

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html